### ISSUE TITLE
Memory leak in PermutateDomainRunner

### ISSUE THREAD

**Issue by fdcarl** [bbb31/slurp#14]
If I leave slurp running for more than a few minutes (at least with the certstream option), memory usage start quickly spiking. Eventually, it gets to the point that all memory is used and it crashes.

As far as I can tell from pprof, it looks like the memory usage is mostly in PermutateDomainRunner. Specifically it points to this line: https://github.com/bbb31/slurp/blob/master/main.go#L256

Unfortunately, I barely understand Golang right now, so I'm not sure how to fix this myself.

**Comment by bbb31** [comment]
I do not believe this to be a memory leak; the program naturally uses a lot of memory (especially if you run it in `certstream` mode and as the `permutations.json` grows).

The code in `PermutateDomainRunner` is where the permutations are created:

```
func PermutateDomainRunner() {
	for {
		dstruct, err := dbQ.Get(1)

		if err != nil {
			log.Error(err)
			continue
		}

		var d Domain = dstruct[0].(Domain)

		//log.Infof("CN: %s\tDomain: %s.%s", d.CN, d.Domain, d.Suffix)

		pd := PermutateDomain(d.Domain, d.Suffix)

		for p := range pd {
			permutatedQ.Put(PermutatedDomain{
				Permutation: pd[p],
				Domain:      d,
			})
		}
	}
}
```

If the memory usage is in `permutatedQ` variable, then its because of the permutations. Previously, I had it check for duplicates but found that a duplicates list for `certstream` domains actually caused it to use more memory. But, I will need more information to confirm that.

The reason why so much memory is used is because computing power creates the permutations faster than they can be processed over the network (this is expected); a hard limit could be put in place for `certstream` but that just means you'll wait longer.
